language: python

python:
    - 3.8

before_install:
    - python --version
    - pip install pip
    - pip install pytest
    - pip install codecov
    - pip install pytest-cov
    - sudo apt-get -y install git cmake build-essential libgl1-mesa-dev mesa-common-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-gfx-dev libboost-all-dev libdirectfb-dev libst-dev mesa-utils xvfb x11vnc libsdl-sge-dev
    - python3 -m pip install --upgrade pip setuptools
    - pip3 install tensorflow==1.15.*
    - pip3 install dm-sonnet==1.*
    - pip3 install git+https://github.com/openai/baselines.git@master

install:
    - pip install -r requirements.txt

script:
    - coverage run -m pytest

after_success:
    - coverage report -m
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - ls
