language: python

services:
    - docker

before_install:
    - docker build --build-arg DOCKER_BASE=ubuntu:18.04 --build-arg DEVICE=cpu . -t soccergen

script:
    - docker ps | grep -q blog
    - pytest
    - coverage run -m pytest

after_success:
    - coverage report -m
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - ls
