language: python

services:
    - docker

before_install:
    - docker build -t pnxenopoulos/soccergen .

script:
    - docker ps | grep -q blog
    - pytest
    - coverage run -m pytest

after_success:
    - coverage report -m
    - bash <(curl -s https://codecov.io/bash)

after_failure:
    - ls
